from __future__ import annotations

# Event-type -> operator remediation mapping. Responses are grounded in the
# Illumio "Events Described" documentation (sourced via NotebookLM 2026-06-29);
# consumed by the alert reporter (src/reporter.py add_event_alert). The legacy
# runbook_url values are retained as metadata but are NOT rendered (stale links).

RUNBOOK_CATEGORIES: dict[str, dict] = {
    "security-auth-failure": {
        "patterns": [
            "request.authentication_failed",
            "request.authorization_failed",
        ],
        "runbook_url": "https://docs.illumio.com/core/24.2/Content/Guides/events-administration/event-types.htm",
        "severity_hint": "critical",
        "response": "When these events trigger, an API request has failed due to authentication or authorization issues. Operators should navigate to the PCE web console under Troubleshooting > Events to review the organization events. Check the event record details for the exception type, exception message, and severity to determine if the failure was a misconfigured API tool or an unauthorized access attempt.",
    },
    "security-auth-activity": {
        "patterns": [
            "user.login",
            "user.logout",
            "user.sign_in",
            "user.sign_out",
            "user.authenticate",
            "user.create_session",
            "user.pce_session_terminated",
            "user.login_session_terminated",
        ],
        "runbook_url": "https://docs.illumio.com/core/24.2/Content/Guides/events-administration/event-types.htm",
        "severity_hint": "info",
        "response": "These events indicate routine user session activities such as authenticating, logging in, and logging out. Operators can view these user actions in the PCE web console by navigating to Troubleshooting > Events. No immediate remediation is required unless the events indicate suspicious patterns, in which case the operator should investigate the associated user and source IP.",
    },
    "security-user-management": {
        "patterns": [
            "user.create",
            "user.delete",
            "user.update",
            "user.invite",
            "user.accept_invitation",
            "user.reset_password",
            "user.update_password",
            "user.use_expired_password",
            "user.verify_mfa",
            "user_local_profile.create",
            "user_local_profile.delete",
            "user_local_profile.reinvite",
            "user_local_profile.update_password",
        ],
        "runbook_url": "https://docs.illumio.com/core/24.2/Content/Guides/user-administration/user-management.htm",
        "severity_hint": "warning",
        "response": "Alerts in this category signify changes to user accounts or RBAC permissions, such as creations, updates, deletions, or invitations. Operators should search for these organization events in the PCE web console under Troubleshooting > Events. Review the event record for the pre-change and post-change values to verify that the access modifications were authorized.",
    },
    "security-api-keys": {
        "patterns": [
            "api_key.create",
            "api_key.delete",
            "api_key.update",
            "service_account.create",
            "service_account.delete",
            "service_account.update",
        ],
        "runbook_url": "https://docs.illumio.com/core/24.2/Content/Guides/rest-api/authentication-and-api-keys.htm",
        "severity_hint": "warning",
        "response": "These events trigger when an API key or credential is created, updated, or deleted. Operators should verify the identity of the user who generated the event by checking the organization events via the PCE web console under Troubleshooting > Events. Check the event records to confirm that the API key lifecycle changes align with expected API administrative operations.",
    },
    "agent-tampering": {
        "patterns": [
            "agent.tampering",
            "agent.clone_detected",
        ],
        "runbook_url": "https://docs.illumio.com/core/24.2/Content/Guides/ven-administration/ven-tampering-protection.htm",
        "severity_hint": "critical",
        "response": "These events alert on potential workload compromise, indicating that an agent's firewall was tampered with or a cloned VEN was detected. Operators should monitor these events closely for high-value workloads and verify if administrative intervention is required, especially if the severity level is marked as an error. Investigate the specific workload details in the PCE web console under Troubleshooting > Events to identify the root cause of the tampering or cloning.",
    },
    "agent-lifecycle": {
        "patterns": [
            "agent.activate",
            "agent.deactivate",
            "agent.suspend",
            "agent.unsuspend",
            "agent.update",
            "agent.goodbye",
            "agent.refresh_token",
            "agent.machine_identifier",
            "agents.unpair",
            "agents.clear_conditions",
        ],
        "runbook_url": "https://docs.illumio.com/core/24.2/Content/Guides/ven-administration/managing-vens.htm",
        "severity_hint": "info",
        "response": "This category tracks when VEN agents are paired, unpaired, suspended, or upgraded. If an agent.suspend event fires unexpectedly, it indicates the workload is no longer protected and may be under attack. Operators should navigate to Troubleshooting > Events in the PCE web console to verify if the lifecycle change was intentional and monitor these events for high-value workloads.",
    },
    "policy-changes": {
        "patterns": [
            "rule_set.create",
            "rule_set.delete",
            "rule_set.update",
            "rule_sets.delete",
            "sec_rule.create",
            "sec_rule.delete",
            "sec_rule.update",
            "sec_policy.create",
            "sec_policy.restore",
            "sec_policy_pending.delete",
            "deny_rule.create",
            "deny_rule.delete",
            "deny_rule.update",
        ],
        "runbook_url": "https://docs.illumio.com/core/24.2/Content/Guides/security-policy/overview-of-security-policy.htm",
        "severity_hint": "warning",
        "response": "These events occur when draft rulesets are created, updated, deleted, or when security policies are provisioned. Operators should review the ruleset scope labels in the event details to ensure they are not unintentionally broad, such as applying to All Applications or All Environments. For policy creation events, verify the workloads_affected field, and if the number exceeds an acceptable threshold, investigate the associated policy changes immediately.",
    },
    "enforcement-boundary": {
        "patterns": [
            "enforcement_boundary.create",
            "enforcement_boundary.delete",
            "enforcement_boundary.update",
        ],
        "runbook_url": "https://docs.illumio.com/core/24.2/Content/Guides/security-policy/enforcement-boundaries.htm",
        "severity_hint": "warning",
        "response": "Alerts in this category are generated when an enforcement boundary is created, updated, or deleted. Operators should review these system modifications in the PCE web console under Troubleshooting > Events. Check the pre-change and post-change values of the affected boundary resources to ensure the modifications were authorized.",
    },
    "workload-changes": {
        "patterns": [
            "workload.create",
            "workload.delete",
            "workload.update",
            "workload.undelete",
            "workload.online",
            "workload.upgrade",
            "workloads.bulk_create",
            "workloads.bulk_delete",
            "workloads.bulk_update",
            "workloads.apply_policy",
            "workloads.unpair",
            "workloads.set_labels",
            "workloads.remove_labels",
        ],
        "runbook_url": "https://docs.illumio.com/core/24.2/Content/Guides/workload-management/workload-operations.htm",
        "severity_hint": "info",
        "response": "These events occur when workload settings are updated, created, or deleted within the system. Operators should inspect the event records in the PCE web console Troubleshooting > Events view to understand what triggered the workload modification. If related lost_agent.found events occur after a workload deletion, operators must send alerts and prepare to pair the VENs with the PCE again.",
    },
    "label-changes": {
        "patterns": [
            "label.create",
            "label.delete",
            "label.update",
            "label_group.create",
            "label_group.delete",
            "label_group.update",
            "labels.delete",
        ],
        "runbook_url": "https://docs.illumio.com/core/24.2/Content/Guides/workload-management/labels-and-label-groups.htm",
        "severity_hint": "info",
        "response": "This category tracks when labels or label groups are created, updated, or deleted. Operators should monitor these events closely because the removed or added labels could represent high-value applications or environments. Review the organization events export to verify that the label modifications correctly reflect intended policy categorizations.",
    },
    "network-infrastructure": {
        "patterns": [
            "network.create",
            "network.delete",
            "network.update",
            "network_device.create",
            "network_device.delete",
            "network_device.update",
            "network_enforcement_node.activate",
            "network_enforcement_node.deactivate",
            "network_enforcement_node.degraded",
            "network_enforcement_node.missed_heartbeats",
        ],
        "runbook_url": "https://docs.illumio.com/core/24.2/Content/Guides/network-enforcement/overview.htm",
        "severity_hint": "warning",
        "response": "These alerts indicate that a network object or SecureConnect gateway has been created, modified, or deleted. Operators should evaluate the pre-change and post-change values of the network resources to confirm the infrastructure changes are expected. View these organization events by selecting Troubleshooting > Events in the PCE web console.",
    },
    "container-events": {
        "patterns": [
            "container_cluster.create",
            "container_cluster.delete",
            "container_cluster.update",
            "container_cluster.security_policy_applied",
            "container_cluster.security_policy_acks",
            "container_workload_profile.create",
            "container_workload_profile.delete",
            "container_workload_profile.update",
        ],
        "runbook_url": "https://docs.illumio.com/core/24.2/Content/Guides/kubernetes-and-openshift/overview.htm",
        "severity_hint": "info",
        "response": "Alerts in this category fire when container clusters or container workload profiles are created, modified, or deleted. Operators can review these actions by navigating to the Troubleshooting > Events page in the PCE web console. Assess the event record details to ensure that any updates to container services align with expected container orchestration changes.",
    },
    "ip-list-changes": {
        "patterns": [
            "ip_list.create",
            "ip_list.delete",
            "ip_list.update",
            "ip_lists.delete",
        ],
        "runbook_url": "https://docs.illumio.com/core/24.2/Content/Guides/security-policy/ip-lists.htm",
        "severity_hint": "warning",
        "response": "These events are triggered when an IP list is created, updated, or deleted. Operators should verify the pre-change and post-change values of the IP list resources to ensure the modified addresses are accurate and authorized. The events can be viewed and verified by exporting the filtered list of organization events from the PCE web console.",
    },
    "auth-config": {
        "patterns": [
            "authentication_settings.update",
            "ldap_config.create",
            "ldap_config.delete",
            "ldap_config.update",
            "saml_config.create",
            "saml_config.delete",
            "saml_config.update",
            "radius_config.create",
            "radius_config.delete",
            "radius_config.update",
        ],
        "runbook_url": "https://docs.illumio.com/core/24.2/Content/Guides/user-administration/authentication-configuration.htm",
        "severity_hint": "critical",
        "response": "These events capture changes to the PCE authentication infrastructure, including LDAP and SAML configurations. Operators must check the PCE web console under Troubleshooting > Events to identify which user or system generated the event. Validate the before and after configuration values to ensure the authentication settings update was authorized, as improper changes could impact user access.",
    },
    "system-tasks": {
        "patterns": [
            "system_task.agent_missed_heartbeats_check",
            "system_task.agent_offline_check",
            "system_task.prune_old_log_events",
            "system_task.compute_policy_for_unmanaged_workloads",
            "system_task.provision_container_cluster_services",
        ],
        "runbook_url": "https://docs.illumio.com/core/24.2/Content/Guides/pce-administration/system-tasks.htm",
        "severity_hint": "info",
        "response": "These alerts indicate routine system tasks or issues where VENs have missed heartbeats and are marked offline. Operators should prioritize missed heartbeat and offline check events for high-value workloads, as the PCE will remove these workloads from policy and alter their security posture. Investigate the affected VENs to determine if they need maintenance or if there is a network connectivity issue causing the missed heartbeats.",
    },
    "server-errors": {
        "patterns": [
            "request.internal_server_error",
            "request.service_unavailable",
            "request.unknown_server_error",
        ],
        "runbook_url": "https://docs.illumio.com/core/24.2/Content/Guides/pce-administration/troubleshooting.htm",
        "severity_hint": "critical",
        "response": "Alerts in this category mean an API request failed due to an internal server error, unavailable service, or unknown server error. Operators should export the filtered organization events from the PCE web console to review the specific failure details. Examine the event record for the exception type, exception message, and severity to aid in troubleshooting the service interruption.",
    },
}

_INDEX = {p: c for c, d in RUNBOOK_CATEGORIES.items() for p in d["patterns"]}


def runbook_for(event_type: str) -> dict | None:
    cat = _INDEX.get(event_type)
    return RUNBOOK_CATEGORIES[cat] if cat else None
